Update README.md
2shady4u/godot-sqlite pull request #120
Opened 2023-01-09 11:53 UTC by feefladder

add description about injection-safeness of query-with-bindings

2023-01-23 12:36 UTC, feefladder commented
#118

2023-01-24 08:13 UTC, 2shady4u requested changes
Hi @feefladder !

Sorry for the long time it took to review this PR.
I have requested some small syntax changes 😄

2023-01-24 08:13 UTC, 2shady4u commented on README.md
> +  will insert a literal `'level+1'` into the database, in stead of incrementing the value by one. In stead, build a direct query like before:
instead is one word

2023-01-24 08:13 UTC, 2shady4u commented on README.md
> +- SQLite's `query_with_bindings` as also used by `update_rows` is injection-safe. That is, any attempt to use sql inside a bound variable will escape it and insert it directly into the record. So the
SQLite's `query_with_bindings`, as also used internally by `update_rows`, is injection-safe.

2023-01-24 08:13 UTC, 2shady4u commented on README.md
> +- SQLite's `query_with_bindings` as also used by `update_rows` is injection-safe. That is, any attempt to use sql inside a bound variable will escape it and insert it directly into the record. So the
inside **of** a bound variable
will escape ~~it~~ and insert it directly

2023-01-24 08:13 UTC, 2shady4u commented on README.md
> +  will insert a literal `'level+1'` into the database, in stead of incrementing the value by one. In stead, build a direct query like before:
What does "like before" mean in this context? Which "before" are we talking about?

2023-01-25 14:17 UTC, feefladder commented on README.md
> +  will insert a literal `'level+1'` into the database, in stead of incrementing the value by one. In stead, build a direct query like before:
I thought it referred to the query-with-bound-column-name example, but that still used `query_with_bindings` in the solution..

2023-01-25 14:17 UTC, feefladder commented
thanks for nitpicking!

2023-01-25 15:56 UTC, 2shady4u approved these changes

2023-01-25 16:01 UTC, merged

2023-01-25 16:02 UTC, 2shady4u commented
Hi @feefladder 

Thank you for the update and apologies for the >2weeks ago it took for me to get to this 😄