Foreign keys delete and update actions
2shady4u/godot-sqlite pull request #197
Opened 2024-12-29 21:23 UTC by Soleyu

Added logic to create table so that it can parse on delete and on update clauses. Now you can just add on_delete and on_cascade directly as  arguments instead of making a query to enable for example on delete cascade.

2024-12-29 21:40 UTC, Soleyu commented
Also, I seem to have polluted it with a commit I did to change something, Im sorry about that Im a bit new with this, on that note, if I did this whole pull request wrong and should have done soemthing else in order to submit stuff then I apologize.

2024-12-30 08:53 UTC, 2shady4u requested changes
Hello @Soleyu
Thank you for working on this 😃 

I would like to request some small changes to the if-statements 😄 

Also, the formatting check job fails atm so that it something you'll need to fix.

2024-12-30 08:53 UTC, 2shady4u commented on src/gdsqlite.cpp
> +					if (column_dict.get("on_delete", false)) {
Should be:
`if (column_dict.has("on_delete")) {`

Since you are checking if the key exists, not if the key is set to true.

2024-12-30 08:53 UTC, 2shady4u commented on src/gdsqlite.cpp
> +					if (column_dict.get("on_update", false)) {
Should be:
`if (column_dict.has("on_update")) {`

Since you are checking if the key exists, not if the key is set to true.

2024-12-30 18:52 UTC, Soleyu commented on src/gdsqlite.cpp
> +					if (column_dict.get("on_update", false)) {
Sure thing! Ill push those changes in a bit and fix the static check as well

2024-12-30 19:14 UTC, Soleyu commented
The last commit should resolve any issues I think. Also thanks for having patiencve with me!

2024-12-31 10:45 UTC, 2shady4u commented
Hello @Soleyu,

Everything seems to be good with the code now 😄 
Would it be possible to squash your commits into one?
(See the Git checlist here: https://docs.godotengine.org/en/latest/contributing/workflow/pr_review_guidelines.html#git-checklist)

2024-12-31 11:36 UTC, Soleyu commented
> Hello @Soleyu,
> 
> Everything seems to be good with the code now 😄 Would it be possible to squash your commits into one? (See the Git checlist here: https://docs.godotengine.org/en/latest/contributing/workflow/pr_review_guidelines.html#git-checklist)

Sure thing! Ill take me a bit as I need to figure out how exactly to do that, but it should be done today.

2024-12-31 11:42 UTC, Soleyu commented
@2shady4u 

Well squashing commits was easier than I expected. Its done now, anything that I should do?

2024-12-31 12:21 UTC, 2shady4u approved these changes

2024-12-31 12:22 UTC, merged

2024-12-31 12:22 UTC, 2shady4u commented
@Soleyu 

It has been merged 😄 
Thank you for your contribution!